color = ""

[default]
  account_id = "acct_18w58MHJf8TNEYM9"
  device_name = "DarakuMBP.local"
  display_name = "favy_st"
  live_mode_api_key = "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"
  live_mode_publishable_key = "pk_live_qVecw5bwac9cUEnjzAW1aKtN"
  test_mode_api_key = "rk_test_518w58MHJf8TNEYM90AFQJ8tD64xZfK74QvW1O7Tw1vK0b1Q11TqTDeQLs0i1OikJvL3U4oQuW3mYrPxWRV63bIgC00ksUFgj1O"
  test_mode_publishable_key = "pk_test_VUzfZxyzIZgRLG9t1WuG19F6"
