color = ""

[default]
  account_id = "acct_18w58MHJf8TNEYM9"
  device_name = "DarakuMBP.local"
  display_name = "favy_st"
  live_mode_api_key = "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"
  live_mode_publishable_key = "pk_live_qVecw5bwac9cUEnjzAW1aKtN"
  test_mode_api_key = "rk_test_518w58MHJf8TNEYM9GujGHNywiVY1h1THWI6cOQbVvFBYAaOJ8ScuWtVwLcM9sQaVku0kOwG9HzpFrAi02i9Ib0O500iVHqTXxi"
  test_mode_publishable_key = "pk_test_VUzfZxyzIZgRLG9t1WuG19F6"
