color = ""

[default]
  account_id = "acct_18w58MHJf8TNEYM9"
  device_name = "DarakuMBP.local"
  display_name = "favy_st"
  live_mode_api_key = "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"
  live_mode_publishable_key = "pk_live_qVecw5bwac9cUEnjzAW1aKtN"
  test_mode_api_key = "rk_test_518w58MHJf8TNEYM9HOXKQ4C07nZBZtkEmUKX6u7WKG8SCEgp327cj9wAjMMCpQttBUCJWkY0o4M03B5VB0HI5Jjt00wOCCHoaL"
  test_mode_publishable_key = "pk_test_VUzfZxyzIZgRLG9t1WuG19F6"
