color = ""

[default]
  account_id = "acct_18w58MHJf8TNEYM9"
  device_name = "DarakuMBP.local"
  display_name = "favy_st"
  live_mode_api_key = "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"
  live_mode_publishable_key = "pk_live_qVecw5bwac9cUEnjzAW1aKtN"
  test_mode_api_key = "rk_test_518w58MHJf8TNEYM9ywIkLTEVl3XSs2tesAgcRJcgptLfTAsqdVmlaUwbZI8FZyRvvoBOXRwSE2yeEtzlZ3J5KX7M00BG0fE3OA"
  test_mode_publishable_key = "pk_test_VUzfZxyzIZgRLG9t1WuG19F6"
