color = ""

[default]
  account_id = "acct_18w58MHJf8TNEYM9"
  device_name = "DarakuMBP.local"
  display_name = "favy_st"
  live_mode_api_key = "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"
  live_mode_publishable_key = "pk_live_qVecw5bwac9cUEnjzAW1aKtN"
  test_mode_api_key = "rk_test_518w58MHJf8TNEYM9n6KUp3aByexIYvA1FndPMKPrZx3hVKFWCQz5wPs0iI6uyI4iEFaix1ZrjhQOic8zH9EcRxpV00lXvG6s2P"
  test_mode_publishable_key = "pk_test_VUzfZxyzIZgRLG9t1WuG19F6"
